"""change course description column

Revision ID: ab641347f01d
Revises: ec4b3d016b9e
Create Date: 2018-06-30 09:32:23.124407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab641347f01d'
down_revision = 'ec4b3d016b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('descriptions', sa.String(length=256), nullable=True))
    op.drop_column('course', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('description', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('course', 'descriptions')
    # ### end Alembic commands ###
